spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: reliablesecretbackup@gmail.com
    password: pcae ezhv ahog jyav
    test-connection: false # проверка подключения при старте приложения
    properties: # эта секция только для gmail
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

#application.backup:
#  app.folder.name:
#  storage.folder.name:
#  master.file.name:
#  app.info.file.name:
