application.backup:
#  file.checker.delay: 2000
#  app.folder.name:
#  storage.folder.name:
#  master.file.name:
#  app.info.file.name:

crypto:
  encode:
    algorithm: Blowfish

  pas:
      algorithm: PBKDF2WithHmacSHA1
  hash:
    algorithm: MD5


