spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/reliable_secret_backup
    password: pass
    username: postgres
  mail:
    host: smtp.gmail.com
    port: 465
    username: reliablesecretbackup@gmail.com
    password: pcae ezhv ahog jyav
    test-connection: false # проверка подключения при старте приложения
    properties: # эта секция только для gmail
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

application.backup:
  app.folder.name: Reliable-backup
  storage.folder.name: Files
  master.file.name: master-file
  app.info.file.name: app-info
